/*
PARTE DEL FRONT:
 configuro mi Store✅

 creo mis action-types✅
 creo mis indexActions✅
 creo mi reducer✅
 creo componentes:
 LANDING✅
 SEARCHBAR✅
 NAVBAR✅
 auxiliares que voy requiriendo>>>
 ERROR✅
 LOAD✅
 los voy a usar en cards
 CARDDRIVER✅
 DRIVERS✅
 PAGINATION✅
 REDUCER✅
 DRIVERDETAIL✅
 HOME✅
 
 FILTERS - REDUCER - ACTIONS AL RESPECTO✅


 FILTRO POR NOMBRE Y POR EDAD PARECE FUNCIONAR CORRECTAMENTE, Y SE COMBINA CON FILTRO DE EQUIPOS.✅
 
 filtro de equipos NO FUNCIONA para los CREADOS, ver que pasa ahi✅ARREGLADO✅
 
 FILTRO DE origen sigue rompiendo, funciona uno  luego ya no mas.ARREGLADO.✅

 FILTRO DE ORIGEN funciona pero no se COMBINA  con los otros, quedo independiente⚠️
 
 FORM ✅⚠️asegurarme de que ande correcto
 
 aplicacion de CSS✅


 REGISTER + ABOUT✅ + LOGIN (extras, no requeridos)







/*
COMPONENTE:
NavBar✅
SearchBar✅
Landing✅


About⚠️mejorar css, agregar otros datos








Reducer✅⚠️
Actions✅⚠️
Store✅


*/
